package com.finabits.hrms.entity;

import com.finabits.hrms.enums.LeaveStatus;
import com.finabits.hrms.enums.LeaveType;
import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "leaves")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Leave {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User user;

    // Dynamic leave type reference
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "leave_type_config_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private LeaveTypeConfig leaveTypeConfig;

    @Column(nullable = false)
    private LocalDate startDate;

    @Column(nullable = false)
    private LocalDate endDate;

    @Column(nullable = false)
    private int totalDays;

    private int paidDays;
    private int unpaidDays;

    @Builder.Default
    private boolean halfDay = false;  // true if half day leave
    private String  halfDaySlot;      // MORNING (10AM-2PM) or AFTERNOON (2PM-6PM)

    @Enumerated(EnumType.STRING)
    private LeaveType leaveType;      // PAID / UNPAID / MIXED

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private LeaveStatus status = LeaveStatus.PENDING;

    @Column(columnDefinition = "TEXT")
    private String reason;

    private String adminComment;

    // Supporting document (e.g. medical certificate)
    private String documentPath;
    private String documentName;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approved_by")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User approvedBy;

    @CreationTimestamp
    private LocalDateTime appliedAt;

    private LocalDateTime actionAt;

    // Auto-generated leave fields
    @Builder.Default
    private boolean autoGenerated = false;

    @Builder.Default
    private Double leaveConsumed = 0.0;  // default 0 — prevents NOT NULL violation
}