package com.sitegenius.hrms.repository;

import com.sitegenius.hrms.entity.Leave;
import com.sitegenius.hrms.entity.User;
import com.sitegenius.hrms.enums.LeaveStatus;
import com.sitegenius.hrms.enums.LeaveType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

public interface LeaveRepository extends JpaRepository<Leave, Long> {

    Page<Leave> findByUser(User user, Pageable pageable);
    Page<Leave> findByStatus(LeaveStatus status, Pageable pageable);
    @Query("SELECT COUNT(l) > 0 FROM Leave l " +
            "WHERE l.user.id = :employeeId " +
            "AND l.status = 'APPROVED' " +
            "AND l.startDate <= :date " +
            "AND l.endDate >= :date")
    boolean isOnApprovedLeaveOnDate(@Param("employeeId") Long employeeId,
                                    @Param("date") LocalDate date);

    // ── Use leaveConsumed (supports 0.5 for half day) ─────────────────────────

    @Query("SELECT COALESCE(SUM(l.leaveConsumed), 0) FROM Leave l WHERE l.user = :user " +
            "AND l.leaveType = :leaveType AND l.status = 'APPROVED' " +
            "AND YEAR(l.startDate) = :year")
    double sumApprovedLeavesByTypeAndYear(User user, LeaveType leaveType, int year);

    @Query("SELECT COALESCE(SUM(l.leaveConsumed), 0) FROM Leave l WHERE l.user = :user " +
            "AND l.status = 'APPROVED' AND YEAR(l.startDate) = :year")
    double sumLeaveConsumedByYear(User user, int year);

    @Query("SELECT COALESCE(SUM(l.leaveConsumed), 0) FROM Leave l WHERE l.user = :user " +
            "AND l.leaveType = 'MIXED' AND l.status = 'APPROVED' " +
            "AND YEAR(l.startDate) = :year")
    double sumApprovedMixedPaidByYear(User user, int year);

    @Query("SELECT COALESCE(SUM(l.unpaidDays), 0) FROM Leave l WHERE l.user = :user " +
            "AND l.leaveType = 'MIXED' AND l.status = 'APPROVED' " +
            "AND YEAR(l.startDate) = :year")
    double sumApprovedMixedUnpaidByYear(User user, int year);

    @Query("SELECT l FROM Leave l WHERE l.user = :user AND l.status = 'APPROVED' " +
            "AND l.startDate <= :date AND l.endDate >= :date")
    List<Leave> findActiveLeaveOnDate(User user, LocalDate date);

    @Query("SELECT COUNT(l) > 0 FROM Leave l WHERE l.user = :user " +
            "AND l.autoGenerated = true AND l.startDate = :date")
    boolean existsAutoGeneratedLeaveOnDate(User user, LocalDate date);

    @Query("SELECT COUNT(DISTINCT l.user) FROM Leave l WHERE l.status = 'APPROVED' " +
            "AND l.startDate <= :date AND l.endDate >= :date")
    long countEmployeesOnLeaveToday(LocalDate date);

    @Query("SELECT l FROM Leave l WHERE l.status = 'APPROVED' " +
            "AND l.startDate <= :date AND l.endDate >= :date")
    List<Leave> findAllApprovedLeavesToday(LocalDate date);
    @Query("""
        SELECT l FROM Leave l
        WHERE l.user   = :user
          AND l.startDate = :date
          AND l.halfDay   = true
          AND l.status    = 'APPROVED'
        """)
    Optional<Leave> findApprovedHalfDayLeaveForDate(User user, LocalDate date);

    @Query("""
        SELECT l FROM Leave l
        WHERE l.user      = :user
          AND l.startDate BETWEEN :from AND :to
          AND l.halfDay   = true
          AND l.status    = 'APPROVED'
        """)
    List<Leave> findApprovedHalfDayLeavesInRange(User user, LocalDate from, LocalDate to);
}

